### ISSUE TITLE
node2vec : TypeError: object of type 'map' has no len()

### ISSUE THREAD

**Issue by AmalNammouchi** [muhanzhang/SEAL#24]
I tried to run the node2vec code on Zachary's karate club network by executing !python3 src/main.py --input graph/karate.edgelist --output emb/karate.emd on google colab but I get this error : 

Walk iteration:
1 / 10
2 / 10
3 / 10
4 / 10
5 / 10
6 / 10
7 / 10
8 / 10
9 / 10
10 / 10
Traceback (most recent call last):
  File "src/main.py", line 104, in <module>
    main(args)
  File "src/main.py", line 100, in main
    learn_embeddings(walks)
  File "src/main.py", line 87, in learn_embeddings
    model = Word2Vec(walks, size=args.dimensions, window=args.window_size, min_count=0, sg=1, workers=args.workers, iter=args.iter)
  File "/usr/local/lib/python3.6/dist-packages/gensim/models/word2vec.py", line 767, in __init__
    fast_version=FAST_VERSION)
  File "/usr/local/lib/python3.6/dist-packages/gensim/models/base_any2vec.py", line 759, in __init__
    self.build_vocab(sentences=sentences, corpus_file=corpus_file, trim_rule=trim_rule)
  File "/usr/local/lib/python3.6/dist-packages/gensim/models/base_any2vec.py", line 936, in build_vocab
    sentences=sentences, corpus_file=corpus_file, progress_per=progress_per, trim_rule=trim_rule)
  File "/usr/local/lib/python3.6/dist-packages/gensim/models/word2vec.py", line 1571, in scan_vocab
    total_words, corpus_count = self._scan_vocab(sentences, progress_per, trim_rule)
  File "/usr/local/lib/python3.6/dist-packages/gensim/models/word2vec.py", line 1556, in _scan_vocab
    total_words += len(sentence)
TypeError: object of type 'map' has no len()

**Comment by AmalNammouchi** [comment]
and if I try to run the main code of SEAL , Main.py I get this error : 

====== begin of gnn configuration ======
| msg_average = 0
======   end of gnn configuration ======
Namespace(cuda=False, data_name='USAir', hop=1, max_nodes_per_hop=None, max_train_num=100000, no_cuda=False, seed=1, test_name=None, test_ratio=0.1, train_name=None, use_attribute=False, use_embedding=False)
Traceback (most recent call last):
  File "Main.py", line 63, in <module>
    if data.has_key('group'):
AttributeError: 'dict' object has no attribute 'has_key'

**Comment by muhanzhang** [comment]
Hi, can you run SEAL using python2 instead? I implemented it using python2. If you want to move to python3, some modifications need to be made.

**Comment by giuliacern** [comment]
Hi! I had the same issues with python3, look at this thread
https://stackoverflow.com/questions/36982858/object-of-type-map-has-no-len-in-python-3/36982926
. I have solved this issue by just replacing every len(sentence) with len(list(sentence)).
