### ISSUE TITLE
Some application problems

### ISSUE THREAD

**Issue by TigerLection** [muhanzhang/SEAL#28]
My English is not very good，please allow me to use Chinese.
张博士你好，我的本科毕设论文是基于图卷积神经网络的社交网络链路预测，想问一下您的SEAL算法能够符合我这个人题目吗？以及我是否可以不配置嵌入与节点属性来完成这个课题？

**Comment by muhanzhang** [comment]
你好。SEAL正好可以符合你的题目。SEAL主要靠学习图结构信息来预测链路，并不一定需要node embedding。只输入subgraphs给SEAL已经足够。加入node embedding有时有帮助，有时甚至会降低性能。

**Comment by TigerLection** [comment]
这几天配置环境，我换了好几个不同的方法，但是由于电脑环境，内存，甚至服务器，但是CUDA总是配置不好，以及服务器没有显卡。。所以想问一下。cpu跑这个OK吗？

**Comment by muhanzhang** [comment]
cpu可以的，pytorch安cpu版，然后Main.py里面cmd_args.mode = 'cpu'

**Comment by TigerLection** [comment]
我尝试了将Main.py中的cmd_args.mode = 'gpu'改成了cpu，运行后出现了这些问题，
`Initializing DGCNN
Traceback (most recent call last):
  File "Main.py", line 146, in <module>
    classifier = classifier.cuda()
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 304, in cuda
    return self._apply(lambda t: t.cuda(device))
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 201, in _apply
    module._apply(fn)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 201, in _apply
    module._apply(fn)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 201, in _apply
    module._apply(fn)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 223, in _apply
    param_applied = fn(param)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 304, in <lambda>
    return self._apply(lambda t: t.cuda(device))
  File "/usr/local/lib/python3.6/dist-packages/torch/cuda/__init__.py", line 196, in _lazy_init
    _check_driver()
  File "/usr/local/lib/python3.6/dist-packages/torch/cuda/__init__.py", line 94, in _check_driver
    raise AssertionError("Torch not compiled with CUDA enabled")
AssertionError: Torch not compiled with CUDA enabled
`前面构造子图这些的都没有问题，想请教一下，DGCNN无法运用cuda会对结构造成影响吗？
同时，祝愿您身体健康、

**Comment by TigerLection** [comment]
我尝试了将Main.py中的cmd_args.mode = 'gpu'改成了cpu，运行后出现了这些问题，
Initializing DGCNN 
Traceback (most recent call last): 
File "Main.py", line 146, in <module>
 classifier = classifier.cuda() 
File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 304, in cuda 
return self._apply(lambda t: t.cuda(device))
 File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 201, in _apply 
module._apply(fn) 
File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 201, in _apply 
module._apply(fn) 
File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 201, in _apply 
module._apply(fn)
 File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 223, in _apply 
param_applied = fn(param) 
File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 304, in <lambda> return self._apply(lambda t: t.cuda(device))
 File "/usr/local/lib/python3.6/dist-packages/torch/cuda/__init__.py", line 196, in _lazy_init_check_driver()
 File "/usr/local/lib/python3.6/dist-packages/torch/cuda/__init__.py", line 94, in _check_driver raise AssertionError("
Torch not compiled with CUDA enabled") AssertionError: Torch not compiled with CUDA enabled 
前面构造子图这些的都没有问题，想请教一下，DGCNN无法运用cuda会对结构造成影响吗？
同时，祝愿您身体健康

**Comment by muhanzhang** [comment]
如果你改成了'cpu'，line 146不会被执行啊

**Comment by TigerLection** [comment]
所以只需要修改最开始的那个cmd_args.mode = 'cpu',后面的不用修改吗？我是把Main.py里面的两个gpu都修改了，那我知道怎么回事了，谢谢张博士

**Comment by TigerLection** [comment]
张博士你好，在运行了readme上面的几个命令后，我尝试使用其他数据来运行，目前有以下几个问题。
1.如果是要使用自己的数据，是通过pytorch_DGCNN里readme的步骤来执行吗？
2.我在运行的时候,出现了unable to import 'smart_open.gcs', disabling that module，请问这个需要解决吗？因为我发现，虽然有这个问题，，但是最后结果仍然能够输出。
3.我在您的data目录里找到了snap的facebook数据，这个与我最开始设定的数据集刚好遗址，我就想尝试运行，但是当我输入python Main.py --data-name facebook后，在Enclosing subgraph extraction begins这一步就没有动静了，最开始我以为是因为cpu处理较慢，需要较长的运行时间，于是我等了4个小时，第一部甚至连1/4都没完成。于是我在这几天给我的电脑装上了双系统，尝试用gpu跑会不会更快，但是在我尝试之后我发现，一个小时之后仍是没有动静。参考了您的test的两个集合，训练集和测试集均有19022个点，可是仍然能够以较快的速度完成，所以想请教以下您这个如何解决。
最后再次感谢您

**Comment by muhanzhang** [comment]
1. 是的，只要你的数据和data里的数据一样格式。
2. 我不记得有用过这个module，应该没有影响。你看看具体的error message，问题是出在SEAL里还是import别的depend on smart_open的library时出了问题？
3. facebook数据比较大，你可以运行时加上 --hop 1 --max-nodes-per-hop 100 --max-train-num 10000试试，这样可以limit subgraph size and subgraph number. 另外，subgraph extraction默认是调用所有cpu并行的，gpu并不会加速。如果cpu核心数多是会加速的。

**Comment by TigerLection** [comment]
谢谢张博士，我现在再去尝试一下，希望您和您的家人健康平安。

**Comment by TigerLection** [comment]
张博士您好，我有个问题想请教一下您，如果只考虑图的拓扑结构，我们构造子图的信息矩阵X的时候是不是只需要对节点进行标记确定其在子图中的相对重要程度确保能准确预测，而不需要剩下的两个量【即显示特征和节点属性】？还是我们直接将这两个量以0处理？
不好意思再次麻烦您了

**Comment by muhanzhang** [comment]
对的，X不需要包含node embedding和attributes。
