### ISSUE TITLE
System crash during subgraph extraction step

### ISSUE THREAD

**Issue by SYLin117** [muhanzhang/SEAL#61]
Hi, I was trying to test my dataset using --train-name and --train-test and it just stuck during the subgraph extraction process, then killed itself.
I only got some nonrelevant error message here, hope this could help:
```
Traceback (most recent call last):
  File "/home/ian/anaconda3/envs/SEAL/lib/python3.7/multiprocessing/pool.py", line 127, in worker
    put((job, i, result))
  File "/home/ian/anaconda3/envs/SEAL/lib/python3.7/multiprocessing/queues.py", line 364, in put
    self._writer.send_bytes(obj)
  File "/home/ian/anaconda3/envs/SEAL/lib/python3.7/multiprocessing/connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/home/ian/anaconda3/envs/SEAL/lib/python3.7/multiprocessing/connection.py", line 397, in _send_bytes
    self._send(header)
  File "/home/ian/anaconda3/envs/SEAL/lib/python3.7/multiprocessing/connection.py", line 368, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe
```

**Comment by muhanzhang** [comment]
Hi, this error is related to multiprocessing in python. You may turn off multiprocessing by appending "--no-parallel" to your command, or try to debug the multiprocessing by using less [workers](https://github.com/muhanzhang/SEAL/blob/ca1f019a15fb0c21796042165b4e6bee73981dd3/Python/util_functions.py#L106) for example.

**Comment by SYLin117** [comment]
got it, thanks for the reply.
