### ISSUE TITLE
Node with same index

### ISSUE THREAD

**Issue by zackzhou0814** [muhanzhang/SEAL#76]
Hi Dr.Zhang
Since the data that I'm using are limited, I want to add more edges such that the node has a link with itself. For example: 1 1, 2 2, 3 3...
However, when I add such data, SEAL returns an error. Is there a way that I can modify SEAL to accept such edges, if so where should I modify it? Or SEAL just does not accept these edges from the baseline? 

Thank you

**Comment by muhanzhang** [comment]
Can you provide the detailed error message?

**Comment by zackzhou0814** [comment]
Yes, so if I have a node with index 1, and an edge 1 1, it will return a key error of this node.
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/home/tzhou/anaconda3/lib/python3.8/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/home/tzhou/anaconda3/lib/python3.8/multiprocessing/pool.py", line 48, in mapstar
    return list(map(*args))
  File "/home/tzhou/SEAL-master/SEAL/Python/util_functions.py", line 177, in parallel_worker
    return subgraph_extraction_labeling(*x)
  File "/home/tzhou/SEAL-master/SEAL/Python/util_functions.py", line 200, in subgraph_extraction_labeling
    nodes.remove(ind[1])
KeyError: 1
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "Main.py", line 182, in <module>
    train_graphs, test_graphs, max_n_label = links2subgraphs(
  File "/home/tzhou/SEAL-master/SEAL/Python/util_functions.py", line 134, in links2subgraphs
    train_graphs = helper(A, train_pos, 1) + helper(A, train_neg, 0)
  File "/home/tzhou/SEAL-master/SEAL/Python/util_functions.py", line 118, in helper
    results = results.get()
  File "/home/tzhou/anaconda3/lib/python3.8/multiprocessing/pool.py", line 771, in get
    raise self._value
KeyError: 1

**Comment by muhanzhang** [comment]
Predicting self-loops is problematic in SEAL, not only in the preprocessing phase, but also in the later node labeling phase. See #55. Thus, I recommend to not use them. To do data augmentation, you can try to increase the number of sampled negative links (since positive links are limited and fixed).

**Comment by zackzhou0814** [comment]
Got it, thank you.
