### ISSUE TITLE
OSError: [Winerror 193] %1 is not an effective win32 application.

### ISSUE THREAD

**Issue by Gaoleo67** [muhanzhang/SEAL#77]
Hi, Dr. Zhang
Hello, when I was trying to run the 'Main.py', there was a question I can't solve. The error is as follows :

Traceback (most recent call last):
  File "D:\ml\link\code\SEAL-master\SEAL-master\Python\Main.py", line 14, in <module>
    from main import *
  File "D:\ml\link\code\SEAL-master\SEAL-master\Python\pytorch_DGCNN-master\main.py", line 14, in <module>
    from DGCNN_embedding import DGCNN
  File "D:\ml\link\code\SEAL-master\SEAL-master\Python\pytorch_DGCNN-master\DGCNN_embedding.py", line 17, in <module>
    from gnn_lib import GNNLIB
  File "D:\ml\link\code\SEAL-master\SEAL-master\Python\pytorch_DGCNN-master/lib\gnn_lib.py", line 87, in <module>
    GNNLIB = _gnn_lib(sys.argv)
  File "D:\ml\link\code\SEAL-master\SEAL-master\Python\pytorch_DGCNN-master/lib\gnn_lib.py", line 12, in __init__
    self.lib = ctypes.CDLL('%s/build/dll/libgnn.so' % dir_path)
  File "D:\PYTH\lib\ctypes\__init__.py", line 374, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: [Winerror 193] %1 is not an effective win32 application.

I tried to run the program using the 32 bit version of python and it didn't work either. Hoping you can help me.
Thank you!!

**Comment by muhanzhang** [comment]
Hi! The pytorch_DGCNN implementation does not support windows. See [issue](https://github.com/muhanzhang/pytorch_DGCNN/issues/36). You can try to use the pytorch_geometric implementation of SEAL [here](https://github.com/facebookresearch/SEAL_OGB). It is faster and uses modern graph deep learning libraries.

**Comment by Gaoleo67** [comment]
Thank you !!!
