### ISSUE TITLE
TypeError: unsupported operand type(s) for +: 'NoneType' and 'NoneType'

### ISSUE THREAD

**Issue by POLARXSSS** [muhanzhang/SEAL#84]
Hi muhan, 我最近使用模型时遇到这个问题不知道怎么解决：
Traceback (most recent call last):
  File "C:\Users\Miao Jiangbei\Desktop\计算机\机器学习\Lab\SEAL\Python\Main.py", line 162, in <module>
    train_graphs, test_graphs, max_n_label = links2subgraphs(
  File "C:\Users\Miao Jiangbei\Desktop\计算机\机器学习\Lab\SEAL\Python\util_functions.py", line 135, in links2subgraphs
    train_graphs = helper(A, train_pos, 1) + helper(A, train_neg, 0)
TypeError: unsupported operand type(s) for +: 'NoneType' and 'NoneType'
我不知道为什么会得到'NoneType'

**Comment by muhanzhang** [comment]
Can you try to set a breakpoint before `g_list` in `helper()` function to see what it prints? Seems the helper does not return any subgraphs, not even an empty list.
